exclude: '^docs/conf.py|^docs/build/'


repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.0.270'
  hooks:
    - id: ruff

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml"]
    additional_dependencies: ["bandit[toml]"]

# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.12.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: 'v1.0.1'
#   hooks:
#   - id: mypy
#     additional_dependencies: [pydantic~=1.10]

# Checks for missing docstrings
# - repo: https://github.com/econchick/interrogate
#   rev: 1.5.0
#   hooks:
#   - id: interrogate
#     exclude: ^(docs/conf.py|setup.py|tests)
#     args: [--config=pyproject.toml]

# finds dead python code
# - repo: https://github.com/jendrikseipp/vulture
#   rev: 'v2.7'
#   hooks:
#     - id: vulture
