# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    # alias for the latest 3.x version available on Read the Docs
    python: "3"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt

# See https://docs.readthedocs.com/platform/stable/config-file/v2.html#search for more options
search:
  ranking:
    reference/*: -2
    reference/experimental/*: -1
