"""
Models package for Synapse Desktop Client backend.

This package contains all data models and schemas used in the application.
Data models are pure data structures without business logic.
"""

from .api_models import (  # Curator models; End curator models
    AuthResponse,
    BulkDownloadRequest,
    BulkDownloadResponse,
    BulkItem,
    BulkItemsResponse,
    BulkUploadRequest,
    BulkUploadResponse,
    CompletionMessage,
    ConnectionStatusMessage,
    CsvTemplateResponse,
    CurationTaskInfo,
    CurationTaskRequest,
    CurationTaskResponse,
    CurationTasksResponse,
    DeleteCurationTaskRequest,
    DeleteRecordSetRequest,
    DirectoryInfo,
    DownloadRequest,
    DownloadStartResponse,
    EnumerateRecordSetsRequest,
    EnumerateRequest,
    EnumerateResponse,
    ErrorResponse,
    FileInfo,
    GenerateCsvTemplateRequest,
    HealthCheckResponse,
    ListCurationTasksRequest,
    LoginRequest,
    LogMessage,
    LogoutResponse,
    LogPollResponse,
    OperationResponse,
    ProfileInfo,
    ProfilesResponse,
    ProgressMessage,
    RecordSetInfo,
    RecordSetRequest,
    RecordSetResponse,
    RecordSetsResponse,
    ScanDirectoryRequest,
    ScanDirectoryResponse,
    ScanSummary,
    TestLoggingResponse,
    UpdateCurationTaskRequest,
    UpdateRecordSetRequest,
    UploadRequest,
    UploadResult,
    UploadStartResponse,
)
from .domain_models import BulkItem as BulkItemModel

__all__ = [
    # API Request Models
    "LoginRequest",
    "DownloadRequest",
    "UploadRequest",
    "EnumerateRequest",
    "BulkDownloadRequest",
    "BulkUploadRequest",
    "ScanDirectoryRequest",
    # Curator Request Models
    "ListCurationTasksRequest",
    "CurationTaskRequest",
    "UpdateCurationTaskRequest",
    "DeleteCurationTaskRequest",
    "EnumerateRecordSetsRequest",
    "RecordSetRequest",
    "UpdateRecordSetRequest",
    "DeleteRecordSetRequest",
    "GenerateCsvTemplateRequest",
    # API Response Models
    "AuthResponse",
    "OperationResponse",
    "DirectoryInfo",
    "ProfileInfo",
    "ProfilesResponse",
    "BulkItemsResponse",
    "FileInfo",
    "ScanSummary",
    "ScanDirectoryResponse",
    "BulkItem",
    "EnumerateResponse",
    "UploadResult",
    "BulkUploadResponse",
    "LogMessage",
    "LogPollResponse",
    "HealthCheckResponse",
    "TestLoggingResponse",
    "DownloadStartResponse",
    "UploadStartResponse",
    "LogoutResponse",
    "BulkDownloadResponse",
    "CompletionMessage",
    "ProgressMessage",
    "ConnectionStatusMessage",
    "ErrorResponse",
    # Curator Response Models
    "CurationTaskInfo",
    "CurationTasksResponse",
    "CurationTaskResponse",
    "RecordSetInfo",
    "RecordSetsResponse",
    "RecordSetResponse",
    "CsvTemplateResponse",
    # Domain Models
    "BulkItemModel",
]
