## example using command-line client to create a data entity
## with provenance

## Note that this assumes you have a .synapseConfig file in
## your home directory so the client can log in automatically

## To try this example, you'll need to substitute entity IDs from
## your session into the commands below where you see placeholders
## such as <synAAAAA>.

## first, let's dump some data into a file
python generate_random_data.py > data.txt

## Create a project in synapse
synapse create -name "provenance test project" Project
#>> Created entity: <synAAAAA>  provenance test project

## Add a couple of entities to our project, first a Data entity...
synapse add -parentid <synAAAAA> -name "data.txt" -description "My randomly generated data" data.txt
#>> Created entity: <synBBBBB>  data.txt from file: data.txt

## ...and a Code entity that holds the script
synapse add -parentid <synAAAAA> -name "generate_random_data.py" -description "Generate data randomly from the normal distribution" -type "Code" generate_random_data.py
#>> Created entity: <synCCCCC>  generate_random_data.py from file: generate_random_data.py

## Add provenance to the effect that the data entity was generated by executing the code entity
synapse set-provenance -id <synBBBBB> -name 'generate random data' -description 'A fabulous script generated this random data' -executed <synCCCCC>
#>> {"used": [{"reference": {"targetId": "<synCCCCC>"}, "wasExecuted": true}], "modifiedOn": "2013-01-24T23:44:25.028Z", "description": "zippety dippety doo", "createdOn": "2013-01-24T23:44:25.028Z", "etag": "dab0a504-d60d-492b-913d-b09592a1c68a", "modifiedBy": "377358", "createdBy": "377358", "id": "1657086", "name": "generate random data"}

## retrieve the activity like this:
synapse get-provenance -id <synBBBBB>
#>> {"used": [{"reference": {"targetId": "<synCCCCC>"}, "wasExecuted": true}], "modifiedOn": "2013-01-24T23:44:25.028Z", "description": "zippety dippety doo", "createdOn": "2013-01-24T23:44:25.028Z", "etag": "dab0a504-d60d-492b-913d-b09592a1c68a", "modifiedBy": "377358", "createdBy": "377358", "id": "1657086", "name": "generate random data"}


## next, derive a new data entity from the existing one by squaring all the elements
python square.py data.txt > squares.txt

## To save a step, you can also specify provenance in the 'synapse add' command
## by first adding the source entities, in this case just the one code entity
synapse add -parentid <synAAAAA> -name "square.py" -description "Square input data" -type "Code" square.py
#>> Created entity: <synDDDDD>  generate_random_data.py from file: generate_random_data.py

## Then add the derived entity, specifying the source entities as either -executed or -used
## Be sure to include the '--' separator between the arguments to -executed (there can be several)
## and the required file argument 'data.txt'
synapse add -parentid <synAAAAA> -name "squares.txt" -description "Squares of randomly generated data" -executed <synDDDDD> -used <synBBBBB> -- squares.txt
#>> Created entity: <synBBBBB>  data.txt from file: data.txt
