# GitHub Action workflow for current release against the Synapse dev backend (running staging code).
name: validate-synapse-release

on:
  workflow_dispatch:

concurrency:
  group: validate-synapse-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-synapse-release:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[boto3,pandas,pysftp,tests,curator]"
      - name: Check for Secret availability
        id: secret-check
        run: |
          if [ -z "${{ secrets.encrypted_d17283647768_key }}" ]  || [ -z "${{ secrets.encrypted_d17283647768_iv }}" ]; then
            echo "secrets_available=false" >> $GITHUB_OUTPUT;
            echo "Secrets for integration tests are not available. Cancelling integration tests.";
            exit 1;
          else
            echo "secrets_available=true" >> $GITHUB_OUTPUT;
          fi
      - name: Run integration tests (if secrets available)
        run: |
          export SYNAPSE_PROFILE="TestUbuntuMaximumPython"
          echo "Using SYNAPSE_PROFILE: $SYNAPSE_PROFILE"

          # decrypt the encrypted test synapse configuration
          openssl aes-256-cbc -K ${{ secrets.encrypted_d17283647768_key }} -iv ${{ secrets.encrypted_d17283647768_iv }} -in test.synapseConfig.enc -out test.synapseConfig -d
          mv test.synapseConfig ~/.synapseConfig

          # build and run a docker container to serve as an SFTP host for our SFTP tests
          docker build -t sftp_tests - < tests/integration/synapseclient/core/upload/Dockerfile_sftp
          docker run -d sftp_tests:latest

          # get the internal IP address of the just launched container
          export SFTP_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))

          printf "[sftp://$SFTP_HOST]\nusername: test\npassword: test\n" >> ~/.synapseConfig

          # add to known_hosts so the ssh connections can be made without any prompting/errors
          mkdir -p ~/.ssh
          ssh-keyscan -H $SFTP_HOST >> ~/.ssh/known_hosts

          # set env vars used in external bucket tests from secrets
          export EXTERNAL_S3_BUCKET_NAME="${{secrets.EXTERNAL_S3_BUCKET_NAME}}"
          export EXTERNAL_S3_BUCKET_AWS_ACCESS_KEY_ID="${{secrets.EXTERNAL_S3_BUCKET_AWS_ACCESS_KEY_ID}}"
          export EXTERNAL_S3_BUCKET_AWS_SECRET_ACCESS_KEY="${{secrets.EXTERNAL_S3_BUCKET_AWS_SECRET_ACCESS_KEY}}"

          pytest -sv --reruns 3 tests/integration -n 8 --ignore=tests/integration/synapseclient/test_command_line_client.py --dist loadscope
